image: node:16

pipelines:
  branches:
    master:
      - step:
          name: Build Storybook & Storybook Static & Deploy Storybook Static
          script:
            - npm install -g bun
            - bun i
            - bun build-storybook
            - bun build-storybook-hud
            - git add ./storybook-*static
            - git commit -m "Pipeline => Build Storybook & Storybook Static"
            - git push origin master --no-verify #update this to desired branch
            - npm run deploy-storybook-static
