#!/bin/bash
# Prevents force-pushing to master
# Prompts to build before push

line1="                                    \n"
line2="************************************\n"
line3="                                    "

separator="$line1$line2$line3"
divider="------------------------------------"

echo "$separator" 
echo "🏁 Pre-push Hook: Checking branch name..."
echo "$divider"


COMMAND=$(grep "git push" ~/.zsh_history | tail -n 1 || grep "git push" ~/.bash_history | tail -n 1 || grep "git push" ~/.history | tail -n 1)
BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ "$BRANCH" == 'master' || "$COMMAND" == *"master"* ]]; then
  echo "🚫 Cannot push to remote master branch, create your own branch and use PR." 
  echo "$separator" && exit 1
fi

if [[ "$BRANCH" == 'development' || "$COMMAND" == *"development"* ]]; then
  echo "🚫 Cannot push to remote development branch, create your own branch and use PR." 
  echo "$separator" && exit 1
fi

echo "✅ Finished checking branch name."
echo "$separator"


exec < /dev/tty
res=""
response1=""
while [[ ! "$response1" =~ ^[yn]$ ]]; do
    read -p "🤨 Build Storybook? (y/n): " response1
    echo "$divider"
    if [[ ! "$response1" =~ ^[yn]$ ]]; then
        echo "🚫 Please enter 'y' or 'n'."
        echo "$divider"
    fi
done

if [ "$response1" == "y" ]; then
    npm run build-storybook || git reset --hard HEAD
    res="y"
else
    echo "🤌 Skipped build-storybook."
    echo "$divider"
fi

echo "$separator"
response2=""
while [[ ! "$response2" =~ ^[yn]$ ]]; do
    read -p "🤨 Build Storybook HUD? (y/n): " response2
    echo "$divider"
    if [[ ! "$response2" =~ ^[yn]$ ]]; then
        echo "🚫 Please enter 'y' or 'n'."
        echo "$divider"
    fi
done

if [ "$response2" == "y" ]; then
    npm run build-storybook-hud || git reset --hard HEAD
    res="y"
else
    echo "🤌 Skipped build-storybook-hud."
    echo "$divider"
fi

if [[ "$res" == "y" ]]; then
    git add .
    git commit --amend --no-edit  --no-verify
    echo "✅ Finish build check!"
    echo "$separator" 
else
    echo "✅ Finish build check!"
    echo "$separator" 
fi

# Continue with other pre-commit tasks or commands

exit 0
